config/routes.rb
Talkthetalk::Application.routes.draw do
  resources :events

  root :to => "events#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :date, :presence => true
  validates :title, :presence => true, :length => { :maximum => 150 }
  validates :speaker, :presence => true, :length => { :maximum => 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


  before_filter :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.xml
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => I18n.t('events_controller.successfully_created', :default => 'Event was successfully created.')) }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => I18n.t('events_controller.successfully_updated', :default => 'Event was successfully updated.')) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('.error_explanation_header', :default => 'Event could not be added due to %{count_errors}: ', :count_errors => pluralize(@event.errors.count, t('.error', :default => 'error'))) %></h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.text_field :date %>
  </div>

  <div class="field">
    <%= f.label :speaker %>
    <%= f.text_field :speaker %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :rows => 8, :cols => 30 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/events/edit.html.erb
<h1><%= t('.header', :default => 'Update event') %></h1>

<%= javascript_tag do %>
  $(document).ready(function() {
    $('#event_date').datetimepicker();
    $('#event_date').datetimepicker('setDate', 
        new Date(<%= @event.date.year %>, <%= @event.date.month-1 %>, <%= @event.date.mday %>, <%= @event.date.hour %>, <%= @event.date.min %>));

  });
<% end %>

<%= render 'form' %>

<%= link_to t('.show', :default => 'Show'), @event %> |
<%= link_to t('.back', :default => 'Back'), events_path %>

app/views/events/index.html.erb
<script language="javascript">
$(document).ready(function() {
    $('#calendar').fullCalendar({
		events: [
			<% @events.each do |event| %>
			{
				'title': '<%= event.title %> - <%= event.speaker %>',
				'start': '<%= event.date.strftime("%a, %d %b %Y %H:%M:%S") %>',
				'url': '/events/<%= event.id %>',
				'description': '<%= event.description.gsub("\r\n", "\\n") %>'
			},
			<% end %>
		],

		weekends: true,
		theme: true,
		aspectRatio: 2,
		allDayDefault: false,

		eventClick: function(event) {
		        if (event.url) {
		            window.open(event.url);
		            return false;
		        }
		},

		eventRender: function(event, element) {
			if (event.description != "") {
				element.qtip({
					content: "<b><%= t('.description', :default => 'Description: ') %></b>" + event.description,
					position: { viewport: $(window) }
				});
			}
		},

		eventBackgroundColor: "#459e00",
		eventBorderColor: "#327e04",
		eventTextColor: "#ffffff",

		monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
		monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
		dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
		dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'],
		buttonText: {
			prev: '&nbsp;&#9668;&nbsp;',
			next: '&nbsp;&#9658;&nbsp;',
			prevYear: '&nbsp;&lt;&lt;&nbsp;',
			nextYear: '&nbsp;&gt;&gt;&nbsp;',
			today: 'hoje',
			month: 'mês',
			week: 'semana',
			day: 'dia'
		},
		allDayText: 'dia todo',
		
		axisFormat: 'H:mm',
		titleFormat: {
			month: 'MMMM yyyy',
			week: "d [ yyyy]{ '&#8212;'[ MMM] d MMM yyyy}",
			day: 'dddd, d MMM, yyyy'
		},
		columnFormat: {
			month: 'ddd',
			week: 'ddd d/M',
			day: 'dddd d/M'
		},
		timeFormat: {
			'': 'H(:mm)tt{ - H:mmtt}',
			agenda: 'H:mmtt{ - H:mmtt}'
		}
    })

});
</script>

<div id="calendar" class="center_aligned"></div>

app/views/events/new.html.erb
<h1><%= t('.header', :default => 'New event') %></h1>

<%= javascript_tag do %>
  $(document).ready(function() {
    $('#event_date').datetimepicker();
  });
<% end %>

<%= render 'form' %>

<%= link_to t('.back', :default => 'Back'), events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= Event.human_attribute_name("date") %>:</b>
  <%= @event.date %>
</p>

<p>
  <b><%= Event.human_attribute_name("title") %>:</b>
  <%= @event.title %>
</p>

<p>
  <b><%= Event.human_attribute_name("description") %>:</b>
  <%= @event.description %>
</p>

<p>
  <b><%= Event.human_attribute_name("speaker") %>:</b>
  <%= @event.speaker %>
</p>


<%= link_to t('.edit', :default => 'Edit'), edit_event_path(@event) %> |
<%= link_to t('.back', :default => 'Back'), events_path %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TalkTheTalk</title>
  <%= javascript_include_tag "prefixfree.min" %>

  <%= javascript_include_tag "jquery-1.7.min" %>
  <%= javascript_include_tag "jquery-ui-1.8.16.custom.min" %>
  <%= javascript_include_tag "jquery-ui-timepicker-addon" %>
  <%= javascript_include_tag "jquery-ui-timepicker-pt-BR" %>
  <%= javascript_include_tag "jquery.datepicker.ui.pt-BR" %>
  <%= javascript_include_tag "jquery.qtip.min" %>

  <%= javascript_include_tag "fullcalendar.min" %>


  <%= stylesheet_link_tag "datetimepicker", "south-street/theme", "jquery.qtip", "fullcalendar", "talkthetalk" %>

  <%= csrf_meta_tag %>
</head>
<body>

<center>
  <div class="headmaster">
    <h1 class="padded"><%= t('.title', :default => 'TalkTheTalk') %></h1>
    <h4 class="padded"><%= t('.subtitle', :default => 'Spread your words') %></h4>
  </div>
</center>

<div class="right">
<a href="/events/new" class="btn"><%= t('.add_event', :default => 'Add event') %></a>
</div>
<br />

<div class="container">
<%= yield %>
</div>


</body>
</html>